disabled_rules:
  - identifier_name
  - type_name
  - cyclomatic_complexity
  - function_body_length
opt_in_rules:
  - sorted_imports

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

trailing_comma:
  mandatory_comma: true

# In this codebase:
# - TODO means we plan to do it in the future and can be committed
# - FIXME means that file should not be committed
todo:
  only: [FIXME]
