disabled_rules:
  - identifier_name
  - type_name
  - cyclomatic_complexity
  - function_body_length
  - file_length
  - type_body_length
  - large_tuple
  - function_parameter_count
opt_in_rules:
  - sorted_imports

trailing_comma:
  mandatory_comma: true

todo:
  only:
    - FIXME
